baseurl: /
languageCode: en-us
title: Carlos Gallego Blogdown
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:slug/
menu:
  main:
    - name: About me
      url: /about/
    - name: GitHub
      url: https://github.com/cgallegom
    - name: LinkedIn
      url: https://www.linkedin.com/in/carlos-gallego-8169351a2/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: "Projects"
    height: 50
    url: favicon
    width: 80
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
